language: python
python:
  - '3.5'

before_script:
  - pip install -r requirements.txt

# safelist
branches:
  only:
    - staging

env: DJANGO_SETTINGS_MODULE="P8_Pur_Beurre.settings"

services:
  - postgresql

script:
  - ./manage.py test

