# Generated by Django 2.1 on 2018-09-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('nutriscore', models.SmallIntegerField()),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('link_openfoodfacts', models.URLField()),
            ],
        ),
    ]
