# Generated by Django 2.1 on 2018-09-17 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pur_beurre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='0', max_length=20, primary_key=True, serialize=False, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='product',
            name='saved_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Marque'),
        ),
        migrations.AlterField(
            model_name='product',
            name='link_openfoodfacts',
            field=models.URLField(verbose_name='URL Openfoodfacts'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutriscore',
            field=models.SmallIntegerField(choices=[(0, 'N/A'), (1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')], default=0),
        ),
    ]
