# Generated by Django 2.1 on 2018-09-17 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pur_beurre', '0002_auto_20180917_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='saved_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Sauvegardé par'),
        ),
    ]
