# Generated by Django 2.1 on 2018-09-17 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pur_beurre', '0003_auto_20180917_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marque'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='link_openfoodfacts',
            field=models.URLField(blank=True, verbose_name='URL Openfoodfacts'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutriscore',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'N/A'), (1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='saved_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Sauvegardé par'),
        ),
    ]
