# Generated by Django 2.1 on 2018-09-20 14:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pur_beurre', '0008_auto_20180920_1354'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='save',
            unique_together={('saved_by', 'saved_product')},
        ),
    ]
